### ISSUE TITLE
Copy to Clipboard Doesn't Work in Firefox

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#12]
The "Copy to Clipboard" button doesn't work in Firefox.

Re-write the implementation of `copyToClipboard()` in `main.js` so that it works in the current version of Firefox and Chrome.

**Comment by VzqzAc** [comment]
Hey I'm handling this! Can you assign it to me?

**Comment by mkasberg** [comment]
Thanks for your interest! This has already been completed in #16.

**Comment by VzqzAc** [comment]
No problem, thanks for letting me know!
