### ISSUE TITLE
Add a seed script in any new language

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#17]
Open a pull request to add a sample script for any scripting language we don't already have. For a language to be included, it needs to be **executable as a script (i.e. with a `#!` shebang) on Ubuntu Linux** (after installing required dependencies), and it needs to be able to parse basic command line arguments (like `-h`). See the existing scripts for examples.

**Read [CONTRIBUTING](https://github.com/mkasberg/script-seed/blob/master/CONTRIBUTING.md) before you open your pull request**, and feel free to ask if you need help getting the tests working. Also, feel free to open an issue proposing the new language you want to add, and we can work through any details there.

If you want to write a language that we already have, consider improving the existing script instead. (We don't want duplicates.). I'm happy to merge substantive improvements (even if they're small), but I'm not interested in useless text changes (like renaming `plant` to `tree`).

As a rough example, see #26.

**Comment by duck2** [comment]
AWK has some applications as a scripting language. I can try writing a seed in it.

There is even a raycaster written in AWK: https://github.com/TheMozg/awk-raycaster

**Comment by mkasberg** [comment]
Seems like it's probably possible. I'm down if you want to try to get it working https://stackoverflow.com/questions/1418245/invoking-a-script-which-has-an-awk-shebang-with-parameters-vars
