### ISSUE TITLE
Add Scala Seed Script

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#2]

**Comment by curranlipsett** [comment]
I will volunteer to take this on. I'm not too familiar with Scala, but I'll give it a shot!

**Comment by mkasberg** [comment]
Sounds great!

[This](https://www.oreilly.com/library/view/scala-cookbook/9781449340292/ch14s11.html) and [this](https://stackoverflow.com/questions/2315912/best-way-to-parse-command-line-parameters) should help you start off.

**Comment by mkasberg** [comment]
Closed by #13!
