### ISSUE TITLE
Add Lua Seed Script

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#20]
Add a Lua "seed" script to the seeds folder. Basically, this would be an executable Lua file (with `#!/usr/bin/env lua` that parses some simple command-line arguments (like -h or -t, see other scripts as examples) and prints a sentence or two to the command line. It's intended to demonstrate how to parse command line arguments and print something to the console in Lua.

See CONTRIBUTING.md, and feel free to ask for help or clarification here.

As a rough example, see #26.

**Comment by dshah2012** [comment]
I can work on this one too. I had worked on this language for a small project few years back.

**Comment by dshah2012** [comment]
PR has been created and test have passed.

**Comment by mkasberg** [comment]
Thanks @dshah2012 

Lua script added in #47
