### ISSUE TITLE
Add Ruby Seed Script

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#3]
Add a Ruby "seed" script to the seeds folder. Basically, this would be an executable Ruby file (with #!/usr/bin/env ruby that parses some simple command-line arguments (like -h or -t, see other scripts as examples) and prints a sentence or two to the command line. It's intended to demonstrate how to parse command line arguments and print something to the console in Ruby.

See [CONTRIBUTING.md](https://github.com/mkasberg/script-seed/blob/master/CONTRIBUTING.md), and feel free to ask for help or clarification here.

**Comment by caseydierking** [comment]
I started working on this before the comments were here. Submitted a pull request. Cool project, it got me diving back into ruby again after a hiatus. Thanks!

**Comment by mkasberg** [comment]
This has been fixed by #9. I'm closing this issue.

@caseydierking , I'll leave your PR open for now and take a closer look at it later today. There's a chance it might have some improvements on the work curranlipsett did, and if so I'll merge in the best parts of both.

Thanks everyone 👍
