### ISSUE TITLE
Add Tcl Seed Script

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#32]
Add a Tcl "seed" script to the seeds folder. Basically, this would be an executable Tcl file (with #!/usr/bin/env tclsh) that parses some simple command-line arguments (like -h or -t, see other scripts as examples) and prints a sentence or two to the command line. It's intended to demonstrate how to parse command line arguments and print something to the console in Tcl.

See CONTRIBUTING.md, and feel free to ask for help or clarification here.

As a rough example, see #26.

**Comment by dshah2012** [comment]
I have added the TCL script with the appropriate changes.

**Comment by mkasberg** [comment]
Thanks!

Fixed in #48
