### ISSUE TITLE
Add Julia Seed Script

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#33]
Add a [Julia](https://julialang.org/) "seed" script to the seeds folder. Basically, this would be an executable Julia file (with #!/usr/bin/env julia) that parses some simple command-line arguments (like -h or -t, see other scripts as examples) and prints a sentence or two to the command line. It's intended to demonstrate how to parse command line arguments and print something to the console in Julila.

See CONTRIBUTING.md, and feel free to ask for help or clarification here.

As a rough example, see #26.

**Comment by dshah2012** [comment]
I can work on this. I was trying to push the changes to new branch, but I received permission denied error.
"remote: Permission to mkasberg/script-seed.git denied to dshah2012."

**Comment by mkasberg** [comment]
Done in #44!
