### ISSUE TITLE
Fix Travis CI Warnings

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#38]
Travis CI is producing some warning and info messages on our builds: https://travis-ci.org/github/mkasberg/script-seed/jobs/733535031/config

![image](https://user-images.githubusercontent.com/12214617/95283913-12a66a00-081a-11eb-99a0-47024a743ad9.png)

Let's fix all of these by editing the `.travis.yml` file at the root of this repository. Here are the docs: https://docs.travis-ci.com/user/customizing-the-build/

- Remove the `sudo` key since it no longer does anything.
- Set the `dist` to the latest LTS version of Ubuntu: `focal` https://docs.travis-ci.com/user/reference/focal/
- Set `os` to `linux` to make that warning go away.
- Set the `language` to `minimal`: https://docs.travis-ci.com/user/languages/minimal-and-generic/

**Comment by ry-v1** [comment]
Can I take up this?

**Comment by mkasberg** [comment]
Yes, please do!

**Comment by ry-v1** [comment]
Submitted pull request #40. Please check.
