### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#39]
Add Dark mode to https://mkasberg.github.io/script-seed/. Similar to what Hacktoberfest does with the switch on their site: https://hacktoberfest.digitalocean.com/

There should be a toggle to switch between light and dark modes.

This shouldn't be terribly hard to implement because the website itself is very simple. It's a single HTML file `index.html` and a single JS file `main.js` with a small CSS file `style.css`. The HTML file also pulls in a highlightjs syntax highlighting style. Consider using one style for light mode and another for dark mode - you can find additional styles at https://highlightjs.org/.

**Comment by rahuldhangar** [comment]
@mkasberg Hi, I am interested in working this out for you. Can you assign this task to me?

**Comment by rahuldhangar** [comment]
@mkasberg I've added the Dark Mode toggle and modified CSS & JS in PR request #41 
Please check the screenshot below and and consider merging it or add label "hacktoberfest-accepted" if they're ok.
![image](https://user-images.githubusercontent.com/7106661/95347873-08987000-08db-11eb-8fcd-a5f2e304aea1.png)

**Comment by mkasberg** [comment]
Thanks for your contribution! Looks great!

**Comment by mkasberg** [comment]
Fixed by #41
