### ISSUE TITLE
Add Perl Seed Script

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#4]

**Comment by sdeseille** [comment]
Hello @mkasberg , 

I will work on that issue if your agree.

regards

**Comment by sdeseille** [comment]
Hi @mkasberg 

Please review my PR.

many thanks

**Comment by mkasberg** [comment]
I did. https://github.com/mkasberg/script-seed/pull/26

**Comment by mkasberg** [comment]
Fixed by #26
