### ISSUE TITLE
Upgrade Bootstrap

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#43]
We're currently using Bootstrap 4.1.3 from a CDN.

https://github.com/mkasberg/script-seed/blob/ba19a35a90404adf5f68e2d5666cb07ded9bb68c/index.html#L8

The latest version is 4.5.2.

Let's upgrade to 4.5.2. You can find the updated bootstrap URL and integrity sha at https://www.bootstrapcdn.com/. (Use the dropdown to see the integrity sha).

**Comment by amohapatra123** [comment]
i want to work on this issue,
please assign it to me.

**Comment by mkasberg** [comment]
Completed by #45! Thanks!
