### ISSUE TITLE
Add a Deno Script Seed

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/script-seed#59]
Add a Deno "seed" script to the seeds folder. Basically, this would be an executable Deno file (with `#!/usr/bin/env -S deno run --allow-net` or similar) that parses some simple command-line arguments (like `-h` or `-t`, see other scripts as examples) and prints a sentence or two to the command line. It's intended to demonstrate how to parse command line arguments and print something to the console in Deno.

We should use a library like Commander to parse the args: https://deno.land/x/cmd@v1.2.0

See CONTRIBUTING.md, and feel free to ask for help or clarification here.

As a rough example, see #26.

**Comment by vigneshrajj** [comment]
Please let me take this issue.
