### ISSUE TITLE
JavaScript add comments with reference links to scripts

### ISSUE THREAD

**Issue by AloyBranCheung** [mkasberg/script-seed#87]
Hi @mkasberg , 

I was wondering if it's possible for me to comment the JavaScript script seed with links to the official documentation for part of hacktoberfest.

**Comment by mkasberg** [comment]
The Javascript seed doesn't need any documentation links since it's not using an arg parsing library, only arrays.

However, the Deno script (essentially JS), uses the Deno flags library, and it would be good to link to the docs there.

**Comment by AloyBranCheung** [comment]
I'm thinking of including these links to the script. Am I on the right track? 

- https://deno.land/std@0.158.0/flags/mod.ts#const-parsedargs--parseargs-options--
- https://deno.land/std@0.158.0/flags/mod.ts?s=parse
- https://deno.land/std@0.158.0/flags/mod.ts?s=ParseOptions
